# apiVersion: v1
# kind: Service
# metadata:
#   name: guestbook-ui
# spec:
#   ports:
#   - port: 80
#     targetPort: 80
#   selector:
#     app: guestbook-ui
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  type: NodePort
  ports:
  - port: 80          # Port for the service
    targetPort: 80     # Port on the pod
    nodePort: 30080    # Optional: Specify a port in the range 30000-32767
  selector:
    app: guestbook-ui
